# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb222046ba56dfa3399edd67c8c941abb534466470a4ab3c093cfa85a2ba3667604ec78a4690c166c16bd8fae7440d868dfb8bdc4aa529208007b7b24cfed99

test:
  secret_key_base: 0e71aba0eb7d9c2536ff48ee3926e15675756dbbc6a1ddc56ff1b9a6db6b70b3c09fe12556b22af7071736a9a0447b69c2a23c362bca212c646176c117e67593

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
